#!/usr/bin/env bash
# install the ufw firewall and setup a few rules on web-01.

apt update
apt install -y ufw

ufw default deny incoming
ufw default allow outgoing
ufw allow 22
ufw allow 'Nginx Full'

ufw enable
